#ifndef _INCLUDE_CAT_SEVERITY_H_
#define _INCLUDE_CAT_SEVERITY_H_

#include <stdint.h>

enum CAT_SEVERITY_VISABILITY : uint16_t
{
    CAT_SEVERITY_VISABILITY_ALL = 0,

    CAT_SEVERITY_VISABILITY_TRACE,
    CAT_SEVERITY_VISABILITY_DEBUG,
    CAT_SEVERITY_VISABILITY_INFO,
    CAT_SEVERITY_VISABILITY_WARN,
    CAT_SEVERITY_VISABILITY_ERROR,
    CAT_SEVERITY_VISABILITY_FATAL,

    // Disable all print messages
    CAT_SEVERITY_VISABILITY_OFF,
};
enum CAT_SEVERITY_TYPE : uint16_t
{
    CAT_SEVERITY_TYPE_TRACE = 0,
    CAT_SEVERITY_TYPE_DEBUG,
    CAT_SEVERITY_TYPE_INFO,
    CAT_SEVERITY_TYPE_WARN,
    CAT_SEVERITY_TYPE_ERROR,
    CAT_SEVERITY_TYPE_FATAL,

    // User defined type, this removes all custom printing formats and colors
    CAT_SEVERITY_TYPE_CUSTOM,
};


#endif /* _INCLUDE_CAT_SEVERITY_H_ */
